const initialTexts = [
    // Existing Texts (1-20)
    { text: "La mecanografía es una habilidad esencial en el mundo digital. Aprender a teclear rápido y con precisión te ahorrará cientos de horas a lo largo de tu vida. Practica cada día para mejorar.", difficulty: "easy", category: "general" },
    { text: "El rápido zorro marrón salta sobre el perro perezoso. Esta frase contiene todas las letras del alfabeto y es perfecta para calentar los dedos antes de empezar una sesión larga.", difficulty: "easy", category: "pangram" },
    { text: "En un lugar de la Mancha, de cuyo nombre no quiero acordarme, no ha mucho tiempo que vivía un hidalgo de los de lanza en astillero, adarga antigua, rocín flaco y galgo corredor.", difficulty: "medium", category: "literature" },
    { text: "La tecnología avanza a pasos agigantados. La inteligencia artificial, el aprendizaje automático y la computación cuántica están redefiniendo lo que es posible en el campo de la informática.", difficulty: "medium", category: "technology" },
    { text: "Es importante mantener una postura correcta al escribir. Siéntate con la espalda recta, los pies planos en el suelo y los codos en un ángulo de noventa grados para evitar lesiones a largo plazo.", difficulty: "easy", category: "health" },
    { text: "JavaScript es un lenguaje de programación interpretado, dialecto del estándar ECMAScript. Se define como orientado a objetos, basado en prototipos, imperativo, débilmente tipado y dinámico.", difficulty: "hard", category: "coding" },
    { text: "El agua es una sustancia cuya molécula está compuesta por dos átomos de hidrógeno y uno de oxígeno. El término agua generalmente se refiere a la sustancia en su estado líquido.", difficulty: "easy", category: "science" },
    { text: "Cien años de soledad es una novela del escritor colombiano Gabriel García Márquez, ganador del Premio Nobel de Literatura. Es considerada una obra maestra de la literatura hispanoamericana.", difficulty: "medium", category: "literature" },
    { text: "Los estornudos pueden viajar a una velocidad de hasta 160 kilómetros por hora. Por eso es tan importante cubrirse la boca y la nariz al estornudar para evitar la propagación de gérmenes.", difficulty: "medium", category: "curiosity" },
    { text: "El teclado QWERTY es la distribución de teclado más común. Fue diseñado y patentado por Christopher Sholes en 1868 y vendido a Remington en 1873.", difficulty: "medium", category: "history" },
    { text: "La fotosíntesis es el proceso bioquímico mediante el cual las plantas convierten materia inorgánica en materia orgánica, aprovechando la energía de la luz solar.", difficulty: "hard", category: "science" },
    { text: "Para programar bien, no solo hay que escribir código que funcione, sino código que sea legible y mantenible para otros desarrolladores. El código limpio es clave.", difficulty: "medium", category: "coding" },
    { text: "El silencio eterno de estos espacios infinitos me aterra. Una frase célebre del filósofo y matemático Blaise Pascal, reflexionando sobre la inmensidad del universo.", difficulty: "hard", category: "philosophy" },
    { text: "Caminante, no hay camino, se hace camino al andar. Al andar se hace el camino, y al volver la vista atrás se ve la senda que nunca se ha de volver a pisar.", difficulty: "medium", category: "poetry" },
    { text: "La entropía es una magnitud física termodinámica que permite medir la parte no utilizable de la energía interna de un sistema. Es una medida del desorden.", difficulty: "hard", category: "science" },
    { text: "El Monte Everest es la montaña más alta de la superficie del planeta Tierra, con una altitud de 8848 metros sobre el nivel del mar.", difficulty: "easy", category: "geography" },
    { text: "La imaginación es más importante que el conocimiento. El conocimiento es limitado, mientras que la imaginación no. Frase atribuida a Albert Einstein.", difficulty: "medium", category: "quotes" },
    { text: "Un algoritmo es un conjunto de instrucciones o reglas definidas y no-ambiguas, ordenadas y finitas que permite, típicamente, solucionar un problema, realizar un cómputo, procesar datos.", difficulty: "hard", category: "coding" },
    { text: "El sistema solar se formó hace unos 4600 millones de años a partir del colapso gravitacional de una nube molecular gigante interestelar.", difficulty: "medium", category: "science" },
    { text: "Don Quijote de la Mancha es una novela escrita por el español Miguel de Cervantes Saavedra. Publicada su primera parte con el título de El ingenioso hidalgo don Quijote de la Mancha a comienzos de 1605.", difficulty: "medium", category: "literature" },

    // New Texts - Science (21-30)
    { text: "Las células madre son células que tienen la capacidad de dividirse y diferenciarse en diversos tipos de células especializadas, y de autorrenovarse para producir más células madre.", difficulty: "hard", category: "science" },
    { text: "La gravedad es un fenómeno natural por el cual los objetos con masa son atraídos entre sí, efecto mayormente observable en la interacción entre los planetas, galaxias y demás objetos.", difficulty: "medium", category: "science" },
    { text: "El ADN, o ácido desoxirribonucleico, es el material que contiene la información hereditaria en los humanos y casi todos los demás organismos.", difficulty: "medium", category: "science" },
    { text: "Los agujeros negros son regiones finitas del espacio en cuyo interior existe una concentración de masa lo suficientemente elevada como para generar un campo gravitatorio tal que ninguna partícula escapa.", difficulty: "hard", category: "science" },
    { text: "La tabla periódica de los elementos clasifica, organiza y distribuye los distintos elementos químicos conforme a sus propiedades y características.", difficulty: "easy", category: "science" },
    { text: "El cerebro humano es el órgano central del sistema nervioso, localizado en la cabeza y protegido por el cráneo. Tiene la misma estructura general que el cerebro de otros mamíferos.", difficulty: "medium", category: "science" },
    { text: "La velocidad de la luz en el vacío es una constante universal con el valor de 299 792 458 metros por segundo, aunque suele aproximarse a 300 000 km/s.", difficulty: "hard", category: "science" },
    { text: "Los volcanes son estructuras geológicas por las que emerge el magma que se divide en lava y gases provenientes del interior de la Tierra.", difficulty: "easy", category: "geography" },
    { text: "La capa de ozono es una zona de la estratosfera terrestre que contiene una concentración relativamente alta de ozono, absorbiendo gran parte de la radiación ultravioleta.", difficulty: "medium", category: "science" },
    { text: "La evolución biológica es el conjunto de cambios en caracteres fenotípicos y genéticos de poblaciones biológicas a través de generaciones.", difficulty: "hard", category: "science" },

    // New Texts - History (31-40)
    { text: "La Revolución Francesa fue un conflicto social y político, con diversos periodos de violencia, que convulsionó Francia y, por extensión de sus implicaciones, a otras naciones de Europa.", difficulty: "medium", category: "history" },
    { text: "Cristóbal Colón completó cuatro viajes a través del Océano Atlántico que llevaron a una conciencia general europea sobre los continentes americanos.", difficulty: "medium", category: "history" },
    { text: "El Imperio Romano fue el tercer periodo de civilización romana en la Antigüedad Clásica, posterior a la República romana y caracterizado por una forma de gobierno autocrática.", difficulty: "medium", category: "history" },
    { text: "La Segunda Guerra Mundial fue un conflicto militar global que se desarrolló entre 1939 y 1945, involucrando a la mayoría de las naciones del mundo.", difficulty: "medium", category: "history" },
    { text: "La caída del Muro de Berlín en 1989 es considerada uno de los eventos más importantes de la historia moderna, simbolizando el fin de la Guerra Fría.", difficulty: "easy", category: "history" },
    { text: "El Renacimiento fue un amplio movimiento cultural que se produjo en Europa Occidental durante los siglos XV y XVI, marcando la transición entre la Edad Media y los inicios de la Edad Moderna.", difficulty: "hard", category: "history" },
    { text: "La Revolución Industrial marca un punto de inflexión en la historia, modificando e influenciando todos los aspectos de la vida cotidiana de una u otra manera.", difficulty: "medium", category: "history" },
    { text: "Cleopatra VII fue la última gobernante de la dinastía ptolemaica del Antiguo Egipto, aunque nominalmente le sobrevivió como faraón su hijo Cesarión.", difficulty: "medium", category: "history" },
    { text: "La llegada del hombre a la Luna el 20 de julio de 1969, con la misión Apolo 11, fue un hito histórico para la humanidad, protagonizado por Neil Armstrong y Buzz Aldrin.", difficulty: "medium", category: "history" },
    { text: "Machu Picchu es una antigua ciudad inca ubicada en los Andes del Perú. Es considerada una obra maestra de la arquitectura y la ingeniería.", difficulty: "easy", category: "history" },

    // New Texts - Literature (41-50)
    { text: "En un agujero en el suelo, vivía un hobbit. No un agujero húmedo, sucio, repugnante, con restos de gusanos y olor a fango, sino un agujero-hobbit, y eso significa comodidad.", difficulty: "medium", category: "literature" },
    { text: "Ser o no ser, esa es la cuestión. ¿Qué es más noble para el espíritu? ¿Sufrir los golpes y dardos de la insultante fortuna, o tomar armas contra un mar de calamidades?", difficulty: "hard", category: "literature" },
    { text: "Cuentan que un día se reunieron en el Cielo todos los vicios y virtudes. El aburrimiento bostezó por tercera vez y la locura, tan loca como siempre, les propuso jugar al escondite.", difficulty: "medium", category: "literature" },
    { text: "Platero es pequeño, peludo, suave; tan blando por fuera, que se diría todo de algodón, que no lleva huesos. Solo los espejos de azabache de sus ojos son duros cual dos escarabajos.", difficulty: "medium", category: "literature" },
    { text: "Volverán las oscuras golondrinas en tu balcón sus nidos a colgar, y otra vez con el ala a sus cristales jugando llamarán.", difficulty: "medium", category: "poetry" },
    { text: "Me gustas cuando callas porque estás como ausente, y me oyes desde lejos, y mi voz no te toca viaja un rato.", difficulty: "easy", category: "poetry" },
    { text: "El Principito es una novela corta y la obra más famosa del escritor y aviador francés Antoine de Saint-Exupéry. Trata temas profundos como el sentido de la vida.", difficulty: "medium", category: "literature" },
    { text: "Crónica de una muerte anunciada reconstruye con precisión de periodista un asesinato real que tuvo lugar en Colombia, obra maestra de Gabriel García Márquez.", difficulty: "medium", category: "literature" },
    { text: "Rayuela es una novela del escritor argentino Julio Cortázar. Puede leerse de varias maneras, saltando capítulos, lo que la convierte en una antinovela o contranovela.", difficulty: "medium", category: "literature" },
    { text: "La sombra del viento es una novela de Carlos Ruiz Zafón que mezcla intriga, suspense, historia y amor. Se ha convertido en un gran éxito de ventas mundial.", difficulty: "easy", category: "literature" },

    // New Texts - Technology & Coding (51-60)
    { text: "Python es un lenguaje de programación de alto nivel cuya filosofía hace hincapié en la legibilidad de su código, se utiliza para desarrollar aplicaciones de todo tipo.", difficulty: "medium", category: "coding" },
    { text: "El Big Data consiste en un proceso que analiza e interpreta grandes volúmenes de datos, tanto estructurados como no estructurados.", difficulty: "medium", category: "technology" },
    { text: "La ciberseguridad es la práctica de defender las computadoras, los servidores, los dispositivos móviles, los sistemas electrónicos, las redes y los datos de ataques maliciosos.", difficulty: "hard", category: "technology" },
    { text: "HTML5 es la quinta revisión importante del lenguaje básico de la World Wide Web, HTML. Especifica dos variantes de sintaxis para HTML: una clásica y una variante XML.", difficulty: "hard", category: "coding" },
    { text: "La nube o cloud computing permite a los usuarios acceder a los mismos archivos y aplicaciones desde casi cualquier dispositivo, ya que los procesos y archivos están en servidores remotos.", difficulty: "medium", category: "technology" },
    { text: "Blockchain es una estructura de datos en la que la información contenida se agrupa en conjuntos (bloques) a los que se les añade metainformación relativa a otro bloque anterior.", difficulty: "hard", category: "technology" },
    { text: "El Internet de las cosas (IoT) describe la red de objetos físicos que llevan incorporados sensores, software y otras tecnologías con el fin de conectar e intercambiar datos.", difficulty: "medium", category: "technology" },
    { text: "Un bug es un error o fallo en un programa de computador o sistema de software que desencadena un resultado indeseado o incorrecto.", difficulty: "easy", category: "coding" },
    { text: "Git es un sistema de control de versiones distribuido, diseñado para manejar todo, desde proyectos pequeños hasta muy grandes, con velocidad y eficiencia.", difficulty: "medium", category: "coding" },
    { text: "CSS (Cascading Style Sheets) es un lenguaje de diseño gráfico para definir y crear la presentación de un documento estructurado escrito en un lenguaje de marcado.", difficulty: "medium", category: "coding" },

    // New Texts - Geography & Nature (61-70)
    { text: "El río Amazonas es el río más largo y caudaloso del mundo, y contiene más agua que el Nilo, el Yangtsé y el Misisipi juntos.", difficulty: "medium", category: "geography" },
    { text: "La Antártida es el continente más austral de la Tierra. Contiene el Polo Sur geográfico y está situada en el hemisferio sur, casi enteramente al sur del círculo polar antártico.", difficulty: "medium", category: "geography" },
    { text: "El desierto del Sahara es el desierto cálido más grande del mundo y el tercero más grande después de la Antártida y el Ártico.", difficulty: "easy", category: "geography" },
    { text: "La Gran Barrera de Coral es el mayor arrecife de coral del mundo. El arrecife está situado en el mar del Coral, frente a la costa de Queensland al noreste de Australia.", difficulty: "medium", category: "geography" },
    { text: "El monte Fuji se encuentra en el centro de Japón, justo al oeste de Tokio. Se le considera un símbolo sagrado del país y uno de sus principales destinos turísticos.", difficulty: "easy", category: "geography" },
    { text: "El clima mediterráneo se caracteriza por inviernos templados y lluviosos y veranos secos y calurosos, con otoños y primaveras variables.", difficulty: "medium", category: "geography" },
    { text: "La selva tropical es un ecosistema con una gran biodiversidad, siendo el hogar de millones de especies de plantas, animales e insectos.", difficulty: "easy", category: "nature" },
    { text: "Los osos polares son carnívoros y se alimentan principalmente de focas. Dependen del hielo marino para cazar, descansar y reproducirse.", difficulty: "easy", category: "nature" },
    { text: "Las auroras boreales son un fenómeno natural que llena el cielo de colores. Se producen cuando las partículas solares chocan con el campo magnético de la Tierra.", difficulty: "medium", category: "nature" },
    { text: "El Gran Cañón es una vistosa y escarpada garganta excavada por el río Colorado en el norte de Arizona, Estados Unidos.", difficulty: "easy", category: "geography" },

    // New Texts - Curiosities & General (71-80)
    { text: "El ajedrez es un juego de estrategia de mucha profundidad, que requiere inteligencia y habilidades tácticas. Se juega sobre un tablero cuadriculado de 8×8 casillas.", difficulty: "medium", category: "hobbies" },
    { text: "La música tiene la capacidad de influir en nuestro estado de ánimo. Escuchar música alegre puede hacernos sentir más felices, mientras que la música triste puede evocar melancolía.", difficulty: "easy", category: "general" },
    { text: "El chocolate se elabora a partir de las semillas del árbol del cacao. Los antiguos mayas y aztecas lo consideraban un alimento sagrado.", difficulty: "easy", category: "curiosity" },
    { text: "Los gatos duermen una media de 12 a 16 horas al día. Son animales crepusculares, lo que significa que son más activos al amanecer y al atardecer.", difficulty: "easy", category: "curiosity" },
    { text: "El idioma español o castellano es una lengua romance procedente del latín hablado. Pertenece al grupo ibérico y es originaria de Castilla, reino medieval de la península ibérica.", difficulty: "medium", category: "general" },
    { text: "Japón está formado por 6852 islas. Las cuatro islas principales son Honshu, Hokkaido, Kyushu y Shikoku, que forman el 97% de la superficie total del país.", difficulty: "medium", category: "geography" },
    { text: "Un año luz es una unidad de longitud utilizada para medir distancias astronómicas que equivale aproximadamente a 9,46 billones de kilómetros.", difficulty: "hard", category: "science" },
    { text: "Leonardo da Vinci fue un polímata florentino del Renacimiento italiano. Fue a la vez pintor, anatomista, arquitecto, paleontólogo, artista, botánico, científico, escritor, escultor.", difficulty: "hard", category: "history" },
    { text: "El colibrí es el único pájaro que puede volar hacia atrás. Sus alas se mueven muy rápido, lo que le permite mantenerse suspendido en el aire.", difficulty: "easy", category: "nature" },
    { text: "La risa tiene múltiples beneficios para la salud: reduce el estrés, mejora el sistema inmunológico y libera endorfinas, las hormonas de la felicidad.", difficulty: "easy", category: "health" }
];
